### ISSUE TITLE
Port Object to JSON as s-c-s processor

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#100]
As a developer, I'd like to port *object-to-json* module from XD to s-c-s repo, so I can use it as *processor* module to build streaming pipeline.

**Acceptance:**
* *object-to-json* as processor module is available in *spring-cloud-stream-modules* repo 
* maven repo includes *object-to-json* module with respective group/artifact/version detail

**Comment by ericbottard** [comment]
This, as well as #101 should not require a module IMHO. Should be supported via `--input/outputType`

**Comment by dturanski** [comment]
Agree. These are obsolete.
