### ISSUE TITLE
Port field-value-counter as s-c-s sink

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#103]
As a developer, I'd like to port *field-value-counter* module from XD to s-c-s repo, so I can use it as *sink* module to build streaming pipeline.

**Acceptance:**
* *field-value-counter* as sink module is available in *spring-cloud-stream-modules* repo 
* maven repo includes *field-value-counter* module with respective group/artifact/version

**Comment by ilayaperumalg** [comment]
This  is addressed in https://github.com/spring-cloud/spring-cloud-stream-modules/pull/116
