### ISSUE TITLE
Custom 'http' port on PCF is not working

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#106]
As a user, I deployed a stream definition in PCF to consume *http* data from a custom port [ex: 9900], but I'm not able to consume data from this port. The stream successfully deploys though.

**Comment by trisberg** [comment]
Opened an issue to set the port during deployment - https://github.com/spring-cloud/spring-cloud-dataflow-admin-cloudfoundry/issues/6

**Comment by trisberg** [comment]
Not sure how useful this would be since you have to access the http module through port 80 either way. The port parameter would just control the port that the app uses internally and wouldn't be visible to the end-user.
