### ISSUE TITLE
HDFS sink fails to gracefully shutdown on PCF

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#108]
As a user, I'm using HDFS sink in a stream definition. Upon successful destruction of the stream, the sink *(i.e: an App in CF)* is not gracefully shutdown. 

This will have to supported at the Diego level. There's an open issue with [Lattice](https://github.com/cloudfoundry-incubator/lattice-release/issues/190) and as well as [Diego](https://www.pivotaltracker.com/n/projects/1003146/stories/103541132).

**Comment by trisberg** [comment]
There is a recent fix to the Java buildpack that works for shutting down the app context. Use  `https://github.com/cloudfoundry/java-buildpack.git#diego-exec` as the buildpack.

**Comment by trisberg** [comment]
The new buildpack is now released, so this should be fixed.
