### ISSUE TITLE
Improve RedisFieldValueCounterRepository

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-stream-modules#138]
Investigate possibility of directly serializing to a Map (instead of a `Set<ZSetOperations.TypedTuple<String>>`) in RedisFieldValueCounterRepository.getZSetData(String counterKey) 

see https://github.com/spring-cloud/spring-cloud-stream-modules/blob/7004eedcf5a8df87eaf8f9a3a796c0dab26ed5c0/field-value-counter-sink/src/main/java/org/springframework/cloud/stream/module/metrics/RedisFieldValueCounterRepository.java#L105

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-app-starters#67
