### ISSUE TITLE
Make gpfdist sink host discovery better

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-stream-modules#160]
We should use same model as previously introduced in SHDP to find host/ip where sink endpoint is running.

**Comment by trisberg** [comment]
What are the plans for making `DefaultHostInfoDiscovery` a shared utility class? Seems wrong to just duplicate the code here.

**Comment by jvalkeal** [comment]
Yes it should be a shared class somewhere. Any ideas of a location?
