### ISSUE TITLE
Align gpfdist sink dependency versions

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-stream-modules#161]
This is mostly for reactor and jdbc drivers. Originally specific jdbc driver version was taken from gpdb docs but we should check if we can use version from boot for both gpdb/hawq. Need to think what to do with reactor version, as parts of reactor code will get rewritten to get better support message ack.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-app-starters#71
