### ISSUE TITLE
Rewrite gpfdist sink jdbc command structure

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-stream-modules#162]
It's probably a good idea to overhaul whole jdbc command structure to get better support for native gpfdist features. Also we need to make communication between messagehandler and jdbc commands bi-directional(to catch failures) so that we can make message acking reliable.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-app-starters#72
