### ISSUE TITLE
Rabbit source module tests need @Rule for when rabbit is not available

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-stream-modules#164]
Currently, one can't build the modules project if rabbit-server is not running locally.

Those tests should be made conditional on the availability of rabbit

**Comment by artembilan** [comment]
@ericbottard , looks like it is here already:
```
/**
 * Abstract base class for JUnit {@link Rule}s that detect the presence of some external resource. If the resource is
 * indeed present, it will be available during the test lifecycle through {@link #getResource()}. If it is not, tests
 * will either fail or be skipped, depending on the value of system property {@value #SCS_EXTERNAL_SERVERS_REQUIRED}.
 *
 * @author Eric Bottard
 * @author Gary Russell
 */
public abstract class AbstractExternalResourceTestSupport<R> implements TestRule {
```
See its `failOrSkip()` for the proper usage.

And those Rabbit Source tests use `RabbitTestSupport` `@Rule`.

Or do you have anything else in mind?

**Comment by ericbottard** [comment]
Weird, I assumed it was not there, as when I ran the build with rabbit off it failed, and it worked as soon as I turned rabbit on.

I'll look into it

**Comment by ericbottard** [comment]
No can do, it fails consistently for me on `PropertiesPopulatedTests` when rabbit is not running

**Comment by artembilan** [comment]
Oh! 
I think the issue that we start Spring Boot with all the stuff before the reaching `TestRule`.
Try with:
```
@ClassRule
public static RabbitTestSupport rabbitAvailable = new RabbitTestSupport();
```

**Comment by ericbottard** [comment]
As soon as you properly initialize the rule, it behaves better :)

**Comment by ericbottard** [comment]
no need for Class rule, we just need to initialize it...

**Comment by artembilan** [comment]
:smile: 

But with the `@ClassRule` we avoid some Boot noise in logs:
```
org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused: connect
	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:58) ~[spring-rabbit-1.5.2.RELEASE.jar:na]
```
and tests run faster.
