### ISSUE TITLE
support for named parameters in ingestQuery for cassandra-sink

### ISSUE THREAD

**Issue by ashu-walmart** [spring-cloud/spring-cloud-stream-modules#183]
IngestQuery for cassandra-sink can be specified as a string but only supports the classic  "?" as a placeholder for values. It requires the incoming JSON payload to have the exact keys matching table column names specified in the input. support for named parameter in the input ":<param>" is very useful for this.

**Comment by artembilan** [comment]
Please, share the sample how would you like to see it.
We can't provide so much because the INGEST contract is:
```
/**
* This is an operation designed for high performance writes. The CQL is used to create a {@link PreparedStatement}
* once, then all row values are bound to that {@link PreparedStatement} and executed against the {@link Session}.
* <p>
* The lengths of the nested {@link List}s must not be less than the number of bind variables in the CQL.
* </p>
* 
* @param cql The CQL
* @param rows The data to bind to the CQL statement
*/
void ingest(String cql, List<List<?>> rows);
```

Actually we do name matching from the incoming `payload`.
See the `PayloadToMatrixTransformer` source code:
```
List<Map<String, Object>> model = this.jsonObjectMapper.fromJson(payload, List.class);
List<List<Object>> data = new ArrayList<>(model.size());
for (Map<String, Object> entity : model) {
	List<Object> row = new ArrayList<>(this.columns.size());
		for (String column : this.columns) {
			Object value = entity.get(column);
```
The JSON property much match the column name from the query. E.g. our test-case with the `Book` entity. We have the query like:
```
ingest-query=insert into book (isbn, title, author, pages, saleDate, inStock) values (?, ?, ?, ?, ?, ?)
```
So, the `Book` entity should have exactly those `isbn`, `title` etc. properties.

Or would you like to have instead of those `?` some placeholders like `:myTitle` and that would be an incoming entity property?

**Comment by ashu-walmart** [comment]
"Or would you like to have instead of those ? some placeholders like :myTitle and that would be an incoming entity property?" >> Yes. exactly. I would do something like this:

`public PayloadToMatrixTransformer(String query) {
            Matcher matcher = PATTERN.matcher(query);
            if (matcher.matches()) {
                String[] columns = StringUtils.delimitedListToStringArray(matcher.group(1), ",", " ");
                String[] values = StringUtils.delimitedListToStringArray(matcher.group(2), ",", " ");
                for (int i = 0; i < columns.length; i++) {
                    if (values[i].equals("?")) {
                        this.columns.add(columns[i]);
                    } **else if (values[i].startsWith(":")){
                        this.columns.add(values[i].substring(1));
                    }**
                }
            } else {
                throw new IllegalArgumentException("Invalid CQL insert query syntax: " + query);
            }
            this.objectMapper.configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true);
        }`

**Comment by ashu-walmart** [comment]
"Or would you like to have instead of those ? some placeholders like :myTitle and that would be an incoming entity property?" >> Yes. exactly. I would do something like this:

`
public PayloadToMatrixTransformer(String query) {
            Matcher matcher = PATTERN.matcher(query);
            if (matcher.matches()) {
                String[] columns = StringUtils.delimitedListToStringArray(matcher.group(1), ",", " ");
                String[] values = StringUtils.delimitedListToStringArray(matcher.group(2), ",", " ");
                for (int i = 0; i < columns.length; i++) {
                    if (values[i].equals("?")) {
                        this.columns.add(columns[i]);
                    } else if (values[i].startsWith(":")){
                        this.columns.add(values[i].substring(1));
                    }
                }
            } else {
                throw new IllegalArgumentException("Invalid CQL insert query syntax: " + query);
            }
            this.objectMapper.configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true);
        }
`

**Comment by ashu-walmart** [comment]
Yes, Exactly. I would do something like this:
```
public PayloadToMatrixTransformer(String query) {
            Matcher matcher = PATTERN.matcher(query);
            if (matcher.matches()) {
                String[] columns = StringUtils.delimitedListToStringArray(matcher.group(1), ",", " ");
                String[] values = StringUtils.delimitedListToStringArray(matcher.group(2), ",", " ");
                for (int i = 0; i < columns.length; i++) {
                    if (values[i].equals("?")) {
                        this.columns.add(columns[i]);
                    } else if (values[i].startsWith(":")){ //code update starts
                        this.columns.add(values[i].substring(1));
                    }// code update ends
                }
            } else {
                throw new IllegalArgumentException("Invalid CQL insert query syntax: " + query);
            }
            this.objectMapper.configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true);
        }
```

**Comment by artembilan** [comment]
I think the better way would be support "named parameter" exactly in the `value()` clause. Something like this:
```
insert into book (isbn, title, author, pages, saleDate, inStock) values (:myIsbn, :myTitle, :foo, ?, ?, ?)
```
And seems for me we would be able to use:
```
statementCreator.createPreparedStatement(cassandraTemplate.getSession())
```
for this purpose to extract parameter names for the provided `payload`
And ... allow to provide something like `--parameters= foo=payload.myFoo \n bar=headers.bar`.

CC @trisberg

**Comment by ashu-walmart** [comment]
Yes, I did mean the "namedParameter" exactly in the `value()` clause. However I do not think we have exposure to the prepared statement inside PayloadToMatrixTransformer. I sense that just pulling from ":<columnName>" may solve this.
```
else if (values[i].startsWith(":")){ //code update starts
                        this.columns.add(values[i].substring(1));
```
this will identify the keys as "myIsbn", "mytitle", etc. so the incoming payload may look something like this and still work:
```
{
	"myIsbn": "absc",
	"myTitle": "Spring Integration Cassandra",
	"Author": "Cassandra Guru",
	"pages": "523",
	"inStock": "true"
}
```

**Comment by artembilan** [comment]
Yes, that might be enough...

What do you think about the contribution? :smile: 

@sabbyanandan , where we can find the CLA agreement for SCS?

Thanks

**Comment by sabbyanandan** [comment]
@artembilan: The CLA section is included in the SCSM [reference guide](http://docs.spring.io/spring-cloud-stream-modules/docs/current-SNAPSHOT/reference/html/building.html#_sign_the_contributor_license_agreement) and the CLA itself is [here](https://support.springsource.com/spring_committer_signup).

@ashu-walmart: Thank you for your consideration!

**Comment by artembilan** [comment]
Thank you @sabbyanandan !
Out of topic: 
The Copyright in the Manual should be updated to the 2016 :wink:

**Comment by ashu-walmart** [comment]
thanks @artembilan, @sabbyanandan. Here comes the pull request!

**Comment by artembilan** [comment]
You shouldn't close the issue until PR isn't accepted.

The CLA confirmation is important before we start to review the PR.
Please, try to follow with the developer process, like here: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc
The general issue that PR should be from the top-level branch not `master`.

But yes: thank you for the contribution!
