### ISSUE TITLE
Add prefix for OOTB application configs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#191]
As a developer, I'd like to add prefix to all the configurations associated with OOTB applications, so we will not run into naming collisions and facilitate persisting the entires in Spring Cloud Config.

**Acceptance:**
- All the OOTB application configurations have prefixes such as log.sink, time.source etc.

**Comment by ericbottard** [comment]
This needs to be discussed further before we implement anything IMHO. Still need to clarify the need, and see how several instances of the same module are expected to be taken care of (*e.g.* the equivalent of `transform --expression=x | transform --expression=y`)

**Comment by jvalkeal** [comment]
Those modules using `port` option complete blows up in CF as it's adding `PORT` env variable.

**Comment by sabbyanandan** [comment]
Depends on spring-cloud/spring-cloud-dataflow#432

**Comment by sabbyanandan** [comment]
spring-cloud/spring-cloud-dataflow#432 generally covers the overall filtering and whitelisting of application properties, so we may not need to explicitly also prefix app names to deploy them in the desired platform.
