### ISSUE TITLE
Add a README for every module

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream-modules#193]
I can see quite a few with no, or inadequate, descriptions. Ideally I'd like to know how to use each one as a standalone app, plus details (examples) of configuration options, and mandatory configuration (e.g. credentials).

**Comment by sabbyanandan** [comment]
@dsyer: We wanted not to duplicate docs, so currently all the docs are in the [reference guide](http://docs.spring.io/spring-cloud-stream-modules/docs/current-SNAPSHOT/reference/html/) itself. That said, we could certainly link the guide in all the READMEs.

**Comment by dsyer** [comment]
Could it work the other way (include all the module READMEs in the main guide)?

**Comment by sabbyanandan** [comment]
The application specific content is categorized into [source, processor, and sink ascii docs](https://github.com/spring-cloud/spring-cloud-stream-modules/blob/master/spring-cloud-stream-modules-docs%2Fsrc%2Fmain%2Fasciidoc%2Findex.adoc). These docs are not just used in SCSM, but also in each SCDF SPI reference guide as includes, too. We will have to explore how to automate it, so there's always one source for docs across all the different guides/readme's. 

We will look into it.

**Comment by markfisher** [comment]
in the same theme of making these modules into reusable libraries, I would prefer the docs be within each module project, then making the high-level doc a derived "view" of those

**Comment by ericbottard** [comment]
I'm also in favor of pulling the READMEs (or sections thereof) _into_ the reference guide, not the other way around
