### ISSUE TITLE
S3 source / sink

### ISSUE THREAD

**Issue by hvandenb** [spring-cloud/spring-cloud-stream-modules#196]
As a user, I'd like to have a S3 compatible source/sink, so I can read/write the payload to a S3 bucket.

Poperties:

- S3 bucket url
- file name
- AWS token

Acceptance:

- s3 source/sink module is available in spring-cloud-stream-modules repo
- maven repo includes s3 module with respective group/artifact/version
- supported properties are documented in the reference guide

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-app-starters#79
