### ISSUE TITLE
Review Spring Intializr design to generate SCSt projects

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#212]
As a developer, I'd like to study the use of `Spring Intializr` to create the project structure that was coded ‘by-hand'.

**points to consider:**
- this can either be via REST API or programmatically
- the input to initialzr should be the application starter project name and the binder type

**Comment by ghillert** [comment]
Git Repo: https://github.com/ghillert/initializr-scs
