### ISSUE TITLE
Unable to use double quotes with gpfdist

### ISSUE THREAD

**Issue by sgulzar-pivotal** [spring-cloud/spring-cloud-stream-modules#218]
One of the prospects is trying to create a stream and passing the table name in double quotes (Their tables are case sensitive) 
```
file --dir="/home/gpadmin/sppglabtests/" --pattern="testin.csv" --mode="lines" | gpfdist --columnDelimiter="," --dbHost="10.x.x.1" --dbName="spdb" --table="Apple" --mode="INSERT"
```

The stream are failing with the following error:
```
SNAP ERROR sqlTaskScheduler-1 gpfdist.GPFDistMessageHandler - Error in load
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [DROP EXTERNAL TABLE Apple_ext_8cab8bd5_1603_4f28_99e6_2db22583c9ff]; nested exception is org.postgresql.util.PSQLException: ERROR: table "apple_ext_8cab8bd5_1603_4f28_99e6_2db22583c9ff" does not exist
```

**Comment by jvalkeal** [comment]
Not really sure what's going on here as I can't reproduce these errors in gpfdist from dataflow(not sure if it'd be any different in XD).

With gpdb/hawq table names are not case sensitive.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-app-starters#80
