### ISSUE TITLE
.settings.xml

### ISSUE THREAD

**Issue by pberman-pivotal** [spring-cloud/spring-cloud-stream-modules#231]
Hello, 
I was following the instructions for  the quickstart, and spent 3 hours wondering why 
mvn clean package 

kept failing, then a colleague told me about the .settings.xml file. I ran 

mvn clean package -s .settings.xml

And was good to go. I think it would be helpful to mention this in the quick start, the existence of this system file.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-app-starters#83
