### ISSUE TITLE
Move SCStM applications to spring-cloud-stream-app-starters

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#238]
As a developer, I'd like to generate SCStM applications as starters using `spring-cloud-stream-app-maven-plugin` and move them to `spring-cloud/spring-cloud-stream-app-starters` repo.

**Acceptance:**
- All existing SCStM applications from `spring-cloud-stream-modules` are converted as starter applications and moved to `spring-cloud-stream-app-starters`
- Docs and testing infrastructure is moved to `spring-cloud-stream-app-starters`
- Existing CI plan is adapted to `spring-cloud/spring-cloud-stream-app-starters`
- References in [project page](http://cloud.spring.io/spring-cloud-stream-modules/) and other related ref. guides is updated

**List of Apps:**

- [x] file sink/source
- [x] http source
- [x] time source
- [x] log sink
- [x] rabbit sink/source
- [x] bridge-processor
- [x] cassandra-sink
- [x] common
- [x] counter-sink
- [x] field-value-counter-sink
- [x] filter-processor
- [x] ftp-sink
- [x] ftp-source
- [x] gemfire-sink
- [x] gpfdist-sink 
- [x] groovy-filter-processor
- [x] groovy-transform-processor
- [x] hdfs-dataset-sink 
- [x] hdfs-sink 
- [x] httpclient-processor
- [x] integration-test-processor
- [x] jdbc-sink 
- [x] jdbc-source 
- [x] jms-source
- [x] load-generator-source
- [x] loggregator-source
- [x] pmml-processor
- [x] rabbit-sink
- [x] rabbit-source
- [x] redis-sink 
- [x] router-sink
- [x] scriptable-transform-processor
- [x] sftp-source  __plus bonus sftp-sink__
- [x] splitter-processor
- [ ] spring-cloud-stream-modules-dependencies
- [ ] spring-cloud-stream-modules-docs
- [x] syslog-source
- [x] tcp-sink
- [x] tcp-source
- [x] throughput-sink
- [x] transform-processor
- [x] trigger-source
- [x] twitterstream-source
- [x] websocket-sink

**Comment by sabbyanandan** [comment]
This needs to be coordinated with spring-cloud/spring-cloud-stream-modules#191

**Comment by garyrussell** [comment]
__WIP__

file sink/source - done
http source - done
time source - done
log sink - done
rabbit sink/source - Gary

**Comment by sabbyanandan** [comment]
Ignored tests will be addressed via: spring-cloud/spring-cloud-stream-app-starters#14
