### ISSUE TITLE
Reconsider to use @TestPropertySource for common integration test properties

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-stream-modules#247]
See https://github.com/spring-projects/spring-boot/issues/5555 for more information

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-app-starters#86

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-task#138
