### ISSUE TITLE
Want to create processor module and sink module which directly read from kafka topic with help of kafka binder available in s-c-s

### ISSUE THREAD

**Issue by sandip0018** [spring-cloud/spring-cloud-stream-modules#259]
Hi @sabbyanandan ,
   I have requirement like i want to read message from kafka topic and process it and want to pass it to sink module, i want to use the kafka binder for this requirement like i want to configure kafka binder in processor module which will read message and process it and pass it to sink so sink can do logic on it.

so can you please help me on this i'am unable to configure processor module with the help of kafka binder available in s-c-s which will do it for me.

it would be great if you can provide small sample code.

Thanks.

**Comment by sabbyanandan** [comment]
Hi,

First of all, this repo is deprecated. Please see [README](https://github.com/spring-cloud/spring-cloud-stream-modules/#please-note-this-project-is-no-longer-actively-developed) for more details. 

We have instructions on how to [create custom applications](http://docs.spring.io/spring-cloud-stream-app-starters/docs/current-SNAPSHOT/reference/htmlsingle/#_creating_custom_artifacts). There are several samples available [[processor](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/transform) / [sink](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/sink)]; perhaps this could be useful as a reference. 

Lastly, as far as you've the kafka binder in the classpath, you'll be able to build your custom apps specifically to pub/sub using kafka. 

```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-stream-binder-kafka</artifactId>
</dependency>
```
