### ISSUE TITLE
Script processor for SCDF

### ISSUE THREAD

**Issue by whummer** [spring-cloud/spring-cloud-stream-modules#53]
I am planning to port the `script` processor from Spring XD to SCDF:
https://github.com/spring-projects/spring-xd/tree/master/modules/processor/script 

Just wanted to ask whether this would be appreciated as PR, and make sure that this is not already in the immediate pipeline from your side, to avoid duplicate work.

**Comment by sabbyanandan** [comment]
Hi @whummer:  Thanks for your interest! Please feel free to submit a PR; the corresponding JIRA issue [here](https://jira.spring.io/browse/XD-3547).

**Comment by whummer** [comment]
Just realized that this is already implemented as `groovy-transform-processor`, closing this issue as obsolete.
