### ISSUE TITLE
Extend groovy-transform tests to cover a case with multiple script variables

### ISSUE THREAD

**Issue by whummer** [spring-cloud/spring-cloud-stream-modules#56]
The JavaDoc in `ScriptVariableProperties` mentions that variables can be specified as comma-separated key-value pairs:

https://github.com/spring-cloud/spring-cloud-stream-modules/blob/master/common/script-variable-generator/src/main/java/org/springframework/cloud/stream/module/common/ScriptVariableProperties.java#L34

However, this does not work currently, because properties of type `java.util.Properties` are loaded as if they were properties files.

https://github.com/spring-projects/spring-framework/blob/d5ee787e1e6653257720afe31ee3f8819cd4605c/spring-core/src/main/java/org/springframework/core/convert/support/StringToPropertiesConverter.java

This means that properties need to be separated using **newlines**, not commas. This should be documented and covered in the tests.

If we change this code:

https://github.com/spring-cloud/spring-cloud-stream-modules/blob/1e2427cf5d41bd71a1c8bd1e4ed9ff954c7eb72f/groovy-transform-processor/src/test/java/org/springframework/cloud/stream/module/transform/GroovyTransformProcessorIntegrationTests.java#L55

from the following line:

```
	@WebIntegrationTest({"script=script.groovy", "variables=limit=5"})
```
... to ...
```
	@WebIntegrationTest({"script=script.groovy", "variables=limit=5,foo=bar"})
```
... then the test fails because we end up with a single variable `limit` with value `5,foo=bar`, whereas the test succeeds if we change the line to: 
```
	@WebIntegrationTest({"script=script.groovy", "variables=limit=5\nfoo=bar"})
```

**Comment by artembilan** [comment]
That's good catch.

I think we'll revise it after introduction `ShorthandMapConverter`. See the discussion in the #55 

Thank you!

**Comment by whummer** [comment]
ok thanks. This is currently a blocker for us as the `groovy-transform` processor becomes practically unusable once you need more than one script variable (unless you can use variablesLocation, which we currently can't).

**Comment by ericbottard** [comment]
I don't think we'll use `ShorthandMapConverter` as the default converter for Maps/Properties (it introduces extra behavior -- namely shorthands -- that we don't want in 99% of cases.).
What you describe is a limitation with the default Spring core/boot converter for maps, that can be worked around as you show (using `\n`).

The problem is made more visible through the s-c-d shell I guess, where the `\n` needs some escaping.

**Comment by artembilan** [comment]
We need there `\n` (or any other OS line separator) just because of `StringToPropertiesConverter` logic:
```
props.load(new ByteArrayInputStream(source.getBytes("ISO-8859-1")));
```
where it delegates to an internal `LineReader`:
```
    /* Read in a "logical line" from an InputStream/Reader, skip all comment
     * and blank lines and filter out those leading whitespace characters
     * (\u0020, \u0009 and \u000c) from the beginning of a "natural line".
     * Method returns the char length of the "logical line" and stores
     * the line in "lineBuf".
     */
```

So, I'm not sure that it would be so big problem, if we will use your, @ericbottard , `ShorthandMapConverter` together with that annotation to restrict the `Converter` permissiveness.

From other side `ShorthandMapConverter` can even cover `newlines` as well to be backward compatible.

**Comment by ericbottard** [comment]
The main purpose of `ShorthandMapConverter` is, as its name suggests, to support the shorthand notation where a value equals its key. If we really are unhappy with the default Properties converter provided by spring core, then we shall write another one, but it should not deal with that "shorthand" thing.

**Comment by artembilan** [comment]
Doh... Of course, @ericbottard !
Thank you for pointing that out one more time :smile: 

Yes, I like the idea to be flexible with the `inline map` syntax, but missed that **shorthand** trick for the `a,b` case. And somehow just only here... :chicken: 

So, we have to choice here:
* Just fix the JavaDoc and add test case on the matter with the `\n` as delimiter
* Introduce some other `Converter<String, Map<String, String>>` to allow more flexible `inline map` syntax

WDYT?

**Comment by ericbottard** [comment]
Well, I think the only drawback of the current situation is that you can't input something that contains a carriage return in it. Not a big deal. So I'd go with solution 1
