### ISSUE TITLE
Port JMS as s-c-s source

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#70]
As a developer, I'd like to move *jms* module from XD to s-c-s-m repo, so I can use it as source to build streaming pipeline. 

**Acceptance:**
* *jms* as source module is available in *spring-cloud-stream-modules* repo 
* maven repo includes *jms* module with respective group/artifact/version detail

**Comment by danlangford** [comment]
:+1: 
also, can i get a JMS sink? :smile:

**Comment by sabbyanandan** [comment]
@danlangford: Thanks for your interest! I've added spring-cloud/spring-cloud-stream-modules#176 - we will address in incremental iterations.

**Comment by sabbyanandan** [comment]
Hi @danlangford: Would you be able to share some use-cases/requirements around the `jms` source and sink applications? How are you planning to use it and what `jms` properties you would want as overrides?

We are thinking about `jms` as another supported binder implementation along with `rabbit`, `kafka`, and `redis`. This implementation might fulfill most of the general purpose ingestion requirements.

**Comment by danlangford** [comment]
Oh I missed the notification asking for use cases. Currently one of the
features of my application is that it sits between various JMS providers .
These are in a variety of different networks and we sort of act as a
broker. Messages may Come in from one client who is putting them in a
public facing Qpid and we need to pull messages off and then put them on a
Queue in a internal hightrust kafka. Another pattern is pulling messages
off of Oracle streams AQ and copying the message it to multiple JMS
implementations like Qpid or Mule messages. In this latter one we will
redact portions of the message before copying it to another queue.

We also poll a folder and read files and turn those into messages and
deliver them to various JMS implementations

We would need to be able to set the correlation ID as well as a large
number of arbitrary properties/headers for use by our clients
