### ISSUE TITLE
Port TCP Client as s-c-s processor

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#73]
As a developer, I'd like to move *tcp-client* module from XD to s-c-s repo, so I can use it as processor to build streaming pipeline. 

**Acceptance:**
* *tcp-client* as source module is available in *spring-cloud-stream-modules* repo 
* maven repo includes *tcp-client* module with respective group/artifact/version detail

**Comment by garyrussell** [comment]
Seems to me that this should be a processor, not a source; similar to http-client.

Not sure why this was made a source in XD.

@ericbottard ??

**Comment by ericbottard** [comment]
Indeed I would write this as a processor today. Back then, it kind of integrated its own source of messages to be transformed. With a trigger-on-steroids that could e.g. generate increasing numbers, this would definitely simplify the setup, with the tcp-client having less responsibility

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-app-starters#47
