### ISSUE TITLE
Port TCP as s-c-s sink

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#81]
As a developer, I'd like to move *tcp* module from XD to s-c-s repo, so I can use it as sink to build streaming pipeline. 
**Acceptance:**
* *tcp* as sink module is available in *spring-cloud-stream-modules* repo 
* maven repo includes *tcp* module with respective group/artifact/version detail

**Comment by markpollack** [comment]
Duplicate of https://github.com/spring-cloud/spring-cloud-stream-modules/issues/72

**Comment by artembilan** [comment]
It doesn't duplicate. It's about Sink, but one - Source.
