### ISSUE TITLE
Port HTTP-Client as s-c-s processor

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#82]
As a developer, I'd like to port *http-client* module from XD to s-c-s repo, so I can use it as *processor* module to build streaming pipeline.
**Acceptance:**
* *http-client* as processor module is available in *spring-cloud-stream-modules* repo 
* maven repo includes *http-client* module with respective group/artifact/version detail

**Comment by artembilan** [comment]
See #60

**Comment by sabbyanandan** [comment]
Thanks @artembilan. I have them connected.
