### ISSUE TITLE
Port Kafka as s-c-s sink

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#92]
As a s-c-d developer, I'd like to move *kafka* module from XD to s-c-s repo, so I can use it as *sink* to build streaming pipeline.

**Acceptance:**
* *kafka* as sink module is available in *spring-cloud-stream-modules* repo 
* maven repo includes *kafka* module with respective group/artifact/version detail 
* Module docs are in ref. guide

**Comment by ilayaperumalg** [comment]
I believe this can be closed to give a way to use explicit destination names in the `Kafka` binder itself (similar to kafka source)?

**Comment by sabbyanandan** [comment]
Yes! Thanks @ilayaperumalg. We will address this requirement through Kafka binder itself.
