### ISSUE TITLE
Port analytic-pmml as s-c-s processor

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#97]
As a developer, I'd like to port *analytic-pmml* module from XD to s-c-s repo, so I can use it as *processor* module to build streaming pipeline.
**Acceptance:**
* *analytic-pmml* as processor module is available in *spring-cloud-stream-modules* repo 
* maven repo includes *analytic-pmml* module with respective group/artifact/version detail

**Comment by markpollack** [comment]
Resolved by b1cb3a38c8b51ec57fa0058312c2c511638a9881
